name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Prepare Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build
      - name: Lint files
        run: pnpm lint
      - name: Run tests
        run: pnpm test:coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
